source 'https://rubygems.org'
ruby '2.3.0' 

gem 'rails', '4.2.5'
gem 'pg'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'therubyracer'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise'
gem 'bcrypt', '~> 3.1.7'
gem 'omniauth-facebook'
gem 'less-rails'
gem 'twitter-bootstrap-rails'
gem 'bootstrap_form'
gem 'carrierwave'
gem 'mini_magick'
gem 'bootstrap-datepicker-rails'
gem 'maskedinput-rails'
gem 'font-awesome-rails'
gem 'jquery-ui-rails'
gem 'gmaps-autocomplete-rails'
gem 'gmaps4rails'
gem 'underscore-rails'
gem 'rails4-autocomplete'
gem 'geokit'
gem 'geokit-rails'
gem 'sort_alphabetical'
gem 'mail_form'
gem 'simple_form'
gem 'kaminari'

group :development, :test do
  gem 'spring'
  gem 'pry-rails'
  gem 'pry'
  gem 'pry-doc'
  gem 'pry-stack_explorer'
  gem 'pry-byebug'
  gem 'pry-rescue'
  gem 'quiet_assets'
  gem 'puma'
  gem 'awesome_print', require: 'ap'
  gem 'rails_real_favicon'
end

group :production do
  gem 'rails_12factor'
  gem 'unicorn'
end